"""Generate committed reference material from the canonical OpenAPI document."""

from __future__ import annotations

from pathlib import Path

from paperclip_mcp.openapi import OperationRegistry


def render_tool_reference(registry: OperationRegistry) -> str:
    """Render a stable, reviewable operation-to-tool mapping."""
    lines = [
        "# Generated MCP tool reference",
        "",
        "<!-- Generated by `paperclip-mcp generate-docs`; do not edit manually. -->",
        "",
        (
            f"This service exposes {len(registry.operations)} Paperclip API operations "
            f"across {len(registry.tags)} tags. `paperclip_list_operations` provides bounded "
            "runtime discovery and `paperclip_call_operation` accepts the stable operation "
            "keys shown below. Every row also has a direct schema-validated MCP tool."
        ),
        "",
        "| Tool | Operation | Tag | Authorization | Summary |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        (
            f"| `{operation.tool_name}` | `{operation.key}` | "
            f"`{operation.tag}` | `{operation.actor}` | "
            f"{_escape(operation.summary)} |"
        )
        for operation in registry.operations
    )
    lines.append("")
    lines.extend(
        [
            "## Input convention",
            "",
            "Direct tools keep URL-template values under `path`, URL query values under "
            "`query`, and JSON payloads under `body`. This avoids collisions between body "
            "and URL fields. Array query parameters follow their OpenAPI `style` and "
            "`explode` rules.",
            "",
            "Three upload operations are missing request schemas in the source document. "
            "Those tools additionally expose a `multipart` compatibility object. File "
            "fields use `{filename, media_type, data_base64}`; this behavior is clearly "
            "marked in each tool description and remains bounded by the configured request "
            "size limit.",
            "",
            "## Result convention",
            "",
            "Results contain `status_code`, `content_type`, selected safe response "
            "headers, `body`, and an `encoding` discriminator. JSON and text are returned "
            "directly; binary bodies use base64. Non-success upstream responses become MCP "
            "tool errors with bounded, credential-redacted excerpts.",
            "",
        ]
    )
    return "\n".join(lines)


def generate_references(output: Path, registry: OperationRegistry) -> Path:
    output.mkdir(parents=True, exist_ok=True)
    destination = output / "mcp-tools.md"
    destination.write_text(render_tool_reference(registry), encoding="utf-8")
    return destination


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")
